apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: newsecrets.informatika.org
spec:
  group: informatika.org
  names:
    plural: newsecrets
    singular: newsecret
    kind: NewSecret
    shortNames:
    - nscrt
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["kind","metadata","data","version"]
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
              properties:
                name:
                  type: string
                namespace:
                  type: string
              required:
              - name
              additionalProperties: false
            data:
              type: string
              format: byte
            version:
              type: string
          additionalProperties: false
      additionalPrinterColumns:
      - name: Data
        type: string
        description: The data of the secret
        JSONPath: .data
      - name: Version
        type: string
        description: The version of the secret
        JSONPath: .version