apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysecrets.example.com
spec:
  group: example.com
  scope: Cluster
  names:
    plural: mysecrets
    singular: mysecret
    kind: MySecret
    shortNames:
    - ms
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              namespace:
                type: string
              data:
                type: object
                additionalProperties:
                  type: string
              stringData:
                type: object
                additionalProperties:
                  type: string
            oneOf:
            - required:
              - data
            - required:
              - stringData
