apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: newsecrets.informatika.org
spec:
  group: informatika.org
  names:
    plural: newsecrets
    singular: newsecret
    kind: NewSecret
    shortNames:
    - nscrt
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["kind","data","version"]
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            data:
              description: The data of the secret. It can be a key-value pair or a file.
              type: object
              properties:
                keyValuePairs:
                  type: object
                  additionalProperties:
                    type: string
                files:
                  type: object
                  additionalProperties:
                    type: string
                    format: byte
            version:
              type: string
      additionalPrinterColumns:
      - name: Data
        type: string
        jsonPath: .data
        description: The data of the secret
      - name: Version
        type: string
        jsonPath: .version
        description: The version of the secret